variable "resource_group_name" {}
variable "location" {}
variable "application_gateway_name" {}
variable "gateway_ip_name" {}
variable "gateway_subnet_id" {}
variable "frontend_port_name" {}
variable "frontend_port_number" {}
variable "frontend_ip_configuration" {}
variable "backend_address_pool_name" {}
variable "backend_ip_addresses" {
    default = []
}
variable "backend_http_settings_name" {}
variable "protocol" {}
variable "probe_name" {}
variable "http_listener_name" {}
variable "routing_rule_name" {}
variable "probe_host" {}
variable "probe_path" {}
variable "appgw_public_ip_id" {}